version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands: 
      - mkdir --parents _readthedocs/html/
      - cp --recursive html/* _readthedocs/html/

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py


